title: Manoverboard Boilerplate
description:
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: manoverboard-alpha
plugins:
  - jekyll-feed
sass:
  sass_dir: _sass #compressed
  style: expanded
collections_dir: collections
include: ["/_images"]
google_maps_javascript_api_key: AIzaSyB-f8eAfO4Eu6qw_BipqOV_L24YF6nHohk

# CloudCannon Options
_options:
  image: # Front matter field
    uploads_dir: "uploads"
  content: # Content Editor and block Editable Regions
    uploads_dir: "uploads"

#cloudcannon:
  data: true

# CloudCannon Field Descriptions
_comments:
  name: This will get converted to the file name

# Collections (Custom Post Types)
collections:
  sections:
    output: true
    _hide_content: true
    permalink: /:name 
  properties:
    output: true
    _hide_content: true
    permalink: /investment/properties/:name 
  general_pages:
    output: true
    _hide_content: true
    permalink: /:name

# Layers
_array_structures:
  # —————————————————————————————————————
  # Properties Blocks
  # —————————————————————————————————————
  property_blocks:
    style: 'modal'
    values:
      # ———
      # Full Width Image
      # ———
      - label: Full Width Image
        icon: insert_photo # fonts.google.com/icons
        value:
          _id: full_w_image # use file name w/ underscores
          image:
          image_alt_text:
          caption:
      # ———
      # Full Width Map
      # ———
      - label: Full Width Map
        icon: location_on # fonts.google.com/icons
        value:
          _id: full_w_map # use file name w/ underscores
          longitude:
          latitude:
          caption:
      # ———
      # Property Location
      # ———
      - label: Property Location
        icon: location_on # fonts.google.com/icons
        value:
          _id: property_location # use file name w/ underscores
          longitude:
          latitude:
          location_heading:
          location_text:
  # —————————————————————————————————————
  # Page Blocks
  # —————————————————————————————————————
  page_blocks:
    style: 'modal'
    values:
      # ———
      # General Content
      # ———
      - label: General Content
        icon: wysiwyg # fonts.google.com/icons
        value:
          _id: general_content # use file name w/ underscores
          general_content_html:
      # ———
      # Full Width Map
      # ———
      - label: Full Width Map
        icon: location_on # fonts.google.com/icons
        value:
          _id: full_w_map # use file name w/ underscores
          longitude:
          latitude:
          caption:
      # ———
      # Image & Sidebar
      # ———
      - label: Image & Sidebar
        icon: mms # fonts.google.com/icons
        value:
          _id: image_sidebar # use file name w/ underscores
          image:
          image_alt_text:
          sidebar_caption_heading:
          sidebar_caption_text:
  # —————————————————————————————————————
  # Section Blocks
  # —————————————————————————————————————
  section_blocks:
    style: 'modal'
    values:
      # ———
      # Intro
      # ———
      - label: Intro
        icon: star_outline # fonts.google.com/icons
        value:
          _id: intro # use file name w/ underscores
          heading:
          content_html:
      # ———
      # General Content
      # ———
      - label: General Content
        icon: wysiwyg # fonts.google.com/icons
        value:
          _id: general_content # use file name w/ underscores
          general_content_html:
      # ———
      # Full Width Image
      # ———
      - label: Full Width Image
        icon: insert_photo # fonts.google.com/icons
        value:
          _id: full_w_image # use file name w/ underscores
          image:
          image_alt_text:
          caption:
      # ———
      # Full Width Map
      # ———
      - label: Full Width Map
        icon: location_on # fonts.google.com/icons
        value:
          _id: full_w_map # use file name w/ underscores
          longitude:
          latitude:
          caption:
      # ———
      # Video Embed
      # ———
      - label: Youtube Embed Code
        icon: movie # fonts.google.com/icons
        value:
          _id: youtube_embed # use file name w/ underscores
          youtube_embed_code_block:
      # ———
      # CTA
      # ———
      - label: CTA
        icon: ads_click # fonts.google.com/icons
        value:
          _id: cta # use file name w/ underscores
          featured_image:
          featured_image_alt:
          heading: 
          text:
          button_link:
          button_text:
      # ———
      # Stats
      # ———
      - label: Stats
        icon: numbers # fonts.google.com/icons
        value:
          _id: stats # use file name w/ underscores
          stat_1_icon_image:
          stat_1_stat:
          stat_1_text:
          stat_2_icon_image:
          stat_2_stat:
          stat_2_text:
          stat_3_icon_image:
          stat_3_stat:
          stat_3_text:
      # ———
      # Image & Sidebar
      # ———
      - label: Image & Sidebar
        icon: mms # fonts.google.com/icons
        value:
          _id: image_sidebar # use file name w/ underscores
          image:
          image_alt_text:
          sidebar_caption_heading:
          sidebar_caption_text:
      # ———
      # Team Section
      # ———
      - label: Team Section
        icon: groups # fonts.google.com/icons
        value:
          _id: team # use file name w/ underscores
          heading:
          team_member:
            - name:
              job_title:
              bio_text:
              image:
              read_more: false
              read_more_html: