title: Manoverboard Boilerplate
description:
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: manoverboard-alpha
plugins:
  - jekyll-feed
sass:
  sass_dir: _sass #compressed
  style: expanded
collections_dir: collections
include: ["/_images"]
google_maps_javascript_api_key: AIzaSyB-f8eAfO4Eu6qw_BipqOV_L24YF6nHohk

# CloudCannon Options
_options:
  image: # Front matter field
    uploads_dir: "uploads"
  content: # Content Editor and block Editable Regions
    uploads_dir: "uploads"

#cloudcannon:
  data: true

# CloudCannon Field Descriptions
_comments:
  title: This can get converted to the file name

# Collections (Custom Post Types)
collections:
  sections:
    output: true
    _hide_content: true
    permalink: /:name 
  properties:
    output: true
    _hide_content: true
    permalink: /:name 
  general_pages:
    output: true
    _hide_content: true
    permalink: /:name 

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
